DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS DETALLE_VENTA;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS PROVEEDOR;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS NOM_FABRICANTE;
DROP TABLE IF EXISTS MODELO;
DROP TABLE IF EXISTS VENTA;
DROP TABLE IF EXISTS TIPO_VENTA;
DROP TABLE IF EXISTS METODO_PAGO;
DROP TABLE IF EXISTS ENVIO;
DROP TABLE IF EXISTS EMPLEADO;
DROP TABLE IF EXISTS CARGO;
DROP TABLE IF EXISTS SUCURSAL;
DROP TABLE IF EXISTS DIRECCION;
DROP TABLE IF EXISTS EDO;
CREATE TABLE METODO_PAGO 
(
	ID int NOT NULL AUTO_INCREMENT AUTO_INCREMENT,
	METODO varchar(20) NOT NULL,
	CONSTRAINT METODO_PAGO_PK PRIMARY KEY (ID)
);

CREATE TABLE TIPO_VENTA
(
	ID int NOT NULL AUTO_INCREMENT,
	VENTA varchar(20) NOT NULL,
	CONSTRAINT TIPO_VENTA_PK PRIMARY KEY (ID)
);

CREATE TABLE ENVIO
(
	ID int NOT NULL AUTO_INCREMENT,
	TIPO_ENVIO varchar(20) NOT NULL,
	COSTO_ENVIO FLOAT DEFAULT 99.00 NOT NULL,
	CONSTRAINT ENVIO_PK PRIMARY KEY (ID)
);

CREATE TABLE CARGO
(
	ID int NOT NULL AUTO_INCREMENT,
	PUESTO varchar(20) NOT NULL,
	CONSTRAINT CARGO_PK PRIMARY KEY (ID)
);

CREATE TABLE EDO
(
	ID int NOT NULL AUTO_INCREMENT,
	ESTADO varchar(20) NOT NULL,
	CONSTRAINT EDO_PK PRIMARY KEY (ID)
);

CREATE TABLE PROVEEDOR
(
	ID int NOT NULL AUTO_INCREMENT,
	NOM_ENCARGADO varchar(50) NOT NULL,
	NOM_EMPRESA varchar(30) NOT NULL,
	LADA SMALLINT DEFAULT 55 NOT NULL,
	TELEFONO varchar(10) NOT NULL,
	CONSTRAINT PROVEEDOR_PK PRIMARY KEY (ID)
);


CREATE TABLE NOM_FABRICANTE
(
	ID int NOT NULL AUTO_INCREMENT,
	FABRICANTE varchar(20) NOT NULL,
	CONSTRAINT NOM_FABRICANTE_PK PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIA
(
	ID int NOT NULL AUTO_INCREMENT,
	CATEGORIA varchar(30) NOT NULL,
	CONSTRAINT CATEGORIA_PK PRIMARY KEY (ID)
);

CREATE TABLE MODELO
(
	ID int NOT NULL AUTO_INCREMENT,
	ANIO smallint  NOT NULL,
	CONSTRAINT MODELO_PK PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTO
(
	ID int NOT NULL AUTO_INCREMENT,
	NOMBRE varchar(100) NOT NULL,
	PRECIO int NOT NULL,
	DESCRIPCION varchar(150) NOT NULL,
	ESPECIFICACIONES varchar(150) NOT NULL,
	ID_CATEGORIA int NOT NULL,
	ID_MODELO int NOT NULL,
	ID_PROVEEDOR int NOT NULL,
	ID_FABRICANTE int NOT NULL,
	CONSTRAINT PRODUCTO_PK PRIMARY KEY (ID),
	CONSTRAINT ID_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID),
	CONSTRAINT ID_MODELO FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID),
	CONSTRAINT ID_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID),
	CONSTRAINT ID_FABRICANTE FOREIGN KEY (ID_FABRICANTE) REFERENCES NOM_FABRICANTE(ID)
);

CREATE TABLE DETALLE_VENTA
(
	ID_PRODUCTO int NOT NULL,
	ID_VENTA int NOT NULL,
	CONSTRAINT DETALLE_VENTA_PK PRIMARY KEY (ID_PRODUCTO,ID_VENTA),
	CONSTRAINT ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID)
);

CREATE TABLE EMPLEADO
(
	ID int NOT NULL AUTO_INCREMENT,
	RFC varchar(10) NOT NULL,
	NOMBRE varchar(30) NOT NULL,
	APELLIDO_PAT varchar(25) NOT NULL,
	APELLIDO_MAT varchar(25) NOT NULL,
	CORREO_E varchar(50) NOT NULL,
	NSS varchar(11) NOT NULL,           
	TELEFONO varchar(10) NOT NULL,     
	ID_DIRECCION int,
	ID_CARGO int,
	ID_SUCURSAL int,
	CONSTRAINT EMPLEADO_PK PRIMARY KEY (ID),
	CONSTRAINT ID_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGO (ID)
	-- FK1
	-- FK2 
);

CREATE TABLE VENTA
(
	ID int NOT NULL AUTO_INCREMENT,
	FECHA_VENTA DATE NOT NULL,
	DEVOLUCION_REALIZADA varchar(2),
	ID_METODO_PAGO int,
	ID_EMPLEADO int,
	ID_ENVIO int,
	ID_TIPO_VENTA int,
	CONSTRAINT VENTA_PK PRIMARY KEY (ID),
	CONSTRAINT ID_METODO_PAGO FOREIGN KEY (ID_METODO_PAGO) REFERENCES METODO_PAGO (ID),
	CONSTRAINT ID_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID),
	CONSTRAINT ID_ENVIO FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO(ID),
	CONSTRAINT ID_TIPO_VENTA FOREIGN KEY (ID_TIPO_VENTA) REFERENCES TIPO_VENTA(ID)
);


CREATE TABLE DIRECCION
(
	ID int NOT NULL AUTO_INCREMENT,
	ALCALDIA varchar(50) NOT NULL,
	COL varchar(30) NOT NULL,
	CP varchar(5) NOT NULL,
	CALLE varchar(50) NOT NULL,
	NUM_EXT TINYINT(2) NOT NULL,
	ID_EDO int NOT NULL,
	CONSTRAINT DIRECCION_PK PRIMARY KEY (ID)
	-- FK3
);

CREATE TABLE SUCURSAL
(
	ID int NOT NULL AUTO_INCREMENT,
	NOMBRE varchar(30) NOT NULL,
	PAG_WEB varchar(50) NOT NULL,
	LADA TINYINT(3) DEFAULT 55 NOT NULL,
	TELEFONO varchar(10) NOT NULL,
	ID_DIRECCION int,
	CONSTRAINT SUCURSAL_PK PRIMARY KEY (ID)
	-- FK4
);

CREATE TABLE CLIENTE
(
	ID int NOT NULL AUTO_INCREMENT,
	NOMBRE varchar(30) NOT NULL,
	APELLIDO_PAT varchar(25) NOT NULL,
	APELLIDO_MAT varchar(25) NOT NULL,
	USUARIO varchar(20) NOT NULL,
	CONTRASENIA varchar(20) NOT NULL,
	CORREO_E varchar(50) NOT NULL,
	TELEFONO varchar(10) NOT NULL,
	ID_DIRECCION int NOT NULL,
	CONSTRAINT CLIENTE_PK PRIMARY KEY (ID)
	-- FK5
);

-- FK0
ALTER TABLE DETALLE_VENTA
ADD CONSTRAINT ID_VENTA FOREIGN KEY (ID_VENTA) REFERENCES VENTA (ID);

-- FK1
ALTER TABLE EMPLEADO 
ADD CONSTRAINT ID_DIRECCION_EMPLEADO FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID);
-- FK2
ALTER TABLE EMPLEADO
ADD CONSTRAINT ID_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL (ID);

-- NOTA: SE USO PORQUE TENIAMOS 3 LLAVES FORANEAS CON EL IDENTIFICADOR "ID_DIRECCION", POR LO QUE NO SE PUEDEN HACER LLAVES FORANEAS CON MISMO IDENTIFICADOR
/* 
ALTER TABLE EMPLEADO
DROP CONSTRAINT ID_DIRECCION;
 */

-- FK3
ALTER TABLE DIRECCION
ADD CONSTRAINT ID_EDO FOREIGN KEY (ID_EDO) REFERENCES EDO(ID);

-- FK4
ALTER TABLE SUCURSAL
ADD CONSTRAINT ID_DIRECCION_SUCURSAL FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID);

-- FK5
ALTER TABLE CLIENTE
ADD CONSTRAINT ID_DIRECCION_CLIENTE FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID);



-- CORRECIONES EN TIPOS DE DATOS
/*
ALTER TABLE EMPLEADO
MODIFY NSS TINYINT(11);

ALTER TABLE EMPLEADO
MODIFY TELEFONO TINYINT(10);
 */
